services:

  zeiterfassung:
    image: urlaubsverwaltung/zeiterfassung:latest
    network_mode: "host"
    environment:
      SERVER_PORT: ${PORT}
      # Database
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/zeiterfassung
      SPRING_DATASOURCE_USERNAME: ${SPRINGUSER}
      SPRING_DATASOURCE_PASSWORD: ${SPRINGPASSWORD}
      # Mail
      ZEITERFASSUNG_MAIL_FROM: zeiterfassung@example.org
      ZEITERFASSUNG_MAIL_FROMDISPLAYNAME: zeiterfassung
      ZEITERFASSUNG_MAIL_REPLYTO: replyto@example.org
      ZEITERFASSUNG_MAIL_REPLYTODISPLAYNAME: replyto
      SPRING_MAIL_HOST: localhost
      SPRING_MAIL_PORT: 1025
      # OpenID Connect identity provider
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-ID: ${KC_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-SECRET: ${KC_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_CLIENT-NAME: ${KC_CLIENT_NAME}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_PROVIDER: default
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_SCOPE: openid,profile,email,roles
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_AUTHORIZATION-GRANT-TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DEFAULT_REDIRECT-URI: http://localhost:${PORT}/login/oauth2/code/{registrationId}
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_DEFAULT_ISSUER-URI: ${KEYCLOAK}/realms/zeiterfassung-realm
      ZEITERFASSUNG_SECURITY_OIDC_SERVER-URL: ${KEYCLOAK}
      ZEITERFASSUNG_SECURITY_OIDC_LOGIN-FORM-URL: ${KEYCLOAK}/oauth2/authorization/default
      ZEITERFASSUNG_SECURITY_OIDC_CLAIM-MAPPERS_GROUP-CLAIM_ENABLED: true
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
    depends_on:
      - postgres
      - mailpit

  postgres:
    image: postgres:16.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: zeiterfassung
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: password${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 1s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
